# This Makefile was generated by the Cake3
# https://github.com/grwlf/cake3

GUARD = .cake3/GUARD_$(1)_$(shell echo $($(1)) | md5sum | cut -d ' ' -f 1)

ifeq ($(MAIN),1)
unexport MAIN

# Main section

URVERSION = $(shell urweb -version)
.PHONY: ./all
./all: ./Makefile ./lib.urp ./test/PreludeTest.exe ./test/PreludeTest.sql
./.cake3/tmp___test_PreludeTest_in_2: ./Makefile ./lib.urp ./test/PreludeTest.ur
	( \
	echo   ;\
	echo $$\/option  ;\
	echo $$\/list  ;\
	echo \.\.\/test\/PreludeTest  ;\
	) > ./.cake3/tmp___test_PreludeTest_in_2
./.cake3/tmp___test_PreludeTest_in_1: ./Makefile ./lib.urp ./test/PreludeTest.ur
	( \
	echo database\ dbname\=PreludeTest\.db  ;\
	echo sql\ \.\.\/test\/PreludeTest\.sql  ;\
	echo library\ \.\.\/  ;\
	) > ./.cake3/tmp___test_PreludeTest_in_1
./.cake3/tmp___lib_in_2: ./Makefile ./src/Prelude.ur
	( \
	echo   ;\
	echo $$\/list  ;\
	echo \.\/src\/Prelude  ;\
	) > ./.cake3/tmp___lib_in_2
./.cake3/tmp___lib_in_1: ./Makefile ./src/Prelude.ur
	echo -n > ./.cake3/tmp___lib_in_1
.PHONY: ./test
./test: ./Makefile ./test/PreludeTest.exe ./test/PreludeTest.sql
.PHONY: ./lib
./lib: ./Makefile ./lib.urp
.INTERMEDIATE: ./.fix-multy1
./.fix-multy1: ./Makefile ./test/PreludeTest.urp $(call GUARD,URVERSION)
	urweb -dbms sqlite ./test/PreludeTest
./lib.urp: ./Makefile ./.cake3/tmp___lib_in_1 ./.cake3/tmp___lib_in_2
	cat ./.cake3/tmp___lib_in_1 > ./lib.urp
	cat ./.cake3/tmp___lib_in_2 >> ./lib.urp
./test/PreludeTest.exe: ./.fix-multy1
./test/PreludeTest.sql: ./.fix-multy1
./test/PreludeTest.urp: ./Makefile ./.cake3/tmp___test_PreludeTest_in_1 ./.cake3/tmp___test_PreludeTest_in_2
	cat ./.cake3/tmp___test_PreludeTest_in_1 > ./test/PreludeTest.urp
	cat ./.cake3/tmp___test_PreludeTest_in_2 >> ./test/PreludeTest.urp
$(call GUARD,URVERSION):
	rm -f .cake3/GUARD_URVERSION_*
	touch $@

else

# Prebuild/postbuild section

ifneq ($(MAKECMDGOALS),clean)

.PHONY: ./all
./all: ./.fix-multy1
.PHONY: ./.cake3/tmp___test_PreludeTest_in_2
./.cake3/tmp___test_PreludeTest_in_2: ./.fix-multy1
.PHONY: ./.cake3/tmp___test_PreludeTest_in_1
./.cake3/tmp___test_PreludeTest_in_1: ./.fix-multy1
.PHONY: ./.cake3/tmp___lib_in_2
./.cake3/tmp___lib_in_2: ./.fix-multy1
.PHONY: ./.cake3/tmp___lib_in_1
./.cake3/tmp___lib_in_1: ./.fix-multy1
.PHONY: ./test
./test: ./.fix-multy1
.PHONY: ./lib
./lib: ./.fix-multy1
.INTERMEDIATE: ./.fix-multy1
./.fix-multy1:
	-mkdir .cake3
	MAIN=1 $(MAKE) -f ./Makefile $(MAKECMDGOALS)
.PHONY: ./lib.urp
./lib.urp: ./.fix-multy1
.PHONY: ./test/PreludeTest.exe
./test/PreludeTest.exe: ./.fix-multy1
.PHONY: ./test/PreludeTest.sql
./test/PreludeTest.sql: ./.fix-multy1
.PHONY: ./test/PreludeTest.urp
./test/PreludeTest.urp: ./.fix-multy1

endif
.PHONY: ./clean
./clean:
	-rm ./.cake3/tmp___lib_in_1 ./.cake3/tmp___lib_in_2 ./.cake3/tmp___test_PreludeTest_in_1 ./.cake3/tmp___test_PreludeTest_in_2 ./lib.urp ./test/PreludeTest.exe ./test/PreludeTest.sql ./test/PreludeTest.urp
	-rm -rf .cake3

endif
