# This Makefile was generated by the Cake3
# https://github.com/grwlf/cake3

GUARD = .cake3/GUARD_$(1)_$(shell echo $($(1)) | md5sum | cut -d ' ' -f 1)

ifeq ($(MAIN),1)
unexport MAIN

# Main section

.PHONY: all
all: ./Makefile ./lib.urp
.PHONY: lib
lib: ./Makefile ./lib.urp
./lib.urp: ./Makefile ./src/Prelude.ur .cake3/tmp__lib_in
	cat .cake3/tmp__lib_in > ./lib.urp
.cake3/tmp__lib_in: ./Makefile
	-rm -rf .cake3/tmp__lib_in
	echo '' >> .cake3/tmp__lib_in
	echo './src/Prelude' >> .cake3/tmp__lib_in

else

# Prebuild/postbuild section

ifneq ($(MAKECMDGOALS),clean)

.PHONY: all
all: .fix-multy1
.PHONY: lib
lib: .fix-multy1
.PHONY: ./lib.urp
./lib.urp: .fix-multy1
.PHONY: .cake3/tmp__lib_in
.cake3/tmp__lib_in: .fix-multy1
.INTERMEDIATE: .fix-multy1
.fix-multy1: 
	-mkdir .cake3
	MAIN=1 $(MAKE) -f ./Makefile $(MAKECMDGOALS)

endif
.PHONY: clean
clean: 
	-rm ./lib.urp .cake3/tmp__lib_in
	-rm -rf .cake3

endif
